version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.dev
    image: natapage/nodejs2025q2-service:latest
    command: npm run start:dev
    ports:
      - '${PORT:-4000}:${PORT:-4000}'
    env_file:
      - .env
    environment:
      PORT: ${PORT:-4000}
      DATABASE_URL: postgresql://${DB_USER:-user}:${DB_PASSWORD:-password}@postgres-db:5432/${DB_NAME:-mydatabase}
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    depends_on:
      - postgres-db
    networks:
      - my-network
    restart: on-failure

  postgres-db:
    image: postgres:16-alpine
    environment:
      POSTGRES_USER: ${DB_USER:-user}
      POSTGRES_PASSWORD: ${DB_PASSWORD:-password}
      POSTGRES_DB: ${DB_NAME:-mydatabase}
    ports:
      - "${DB_PORT:-5432}:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - my-network
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${DB_USER:-user} -d ${DB_NAME:-mydatabase}" ]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres-data:

networks:
  my-network:
    driver: bridge
